version: '3.8'


services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


  bot_tg:
    build: /BotProject/
    environment:
      - TOKEN=6706177093:AAEwQQfr_pqmtnukAog6bTqom1hbHDRdLts
    depends_on:
      - db